cake-build/cake-vscode

.gitignore, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, .vscodeignore, README.md, package.json, src/bootstrapper.ts, src/cakeExtension.ts, test/bootstrapper.test.ts, test/index.ts, test/memorystream.ts, tsconfig.json, typings/node.d.ts, typings/vscode-typings.d.ts
This command installs the Cake's bootstrapper to the platform selected
by user. The bootstrapper is downloaded from the Cake repository and
saved in the root folder.
Unfortunately the VSCode doesn't have a UI control that allow multiple
item selection, therefore the user needs to run the command for each
platform they needs the bootstrapper.
To make the user's life a little bit easier, the platform on which it
is running VSCode will always be displayed on top of the list, that way
he can select the item just pressing `ENTER`
=> Adds a command to download Cake bootstrapper

syntaxes/cake.json
The regex for matching keywords for syntax highlighting will include the trailing `(` and colorize it: 
This PR adds a capture to fix:
=> GH25: Fix syntax highlighting on keywords

.gitignore
In line with the recommended way of excluding things from the
github example .gitignore
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
Issue #66
=> Update .gitignore for tools folder (Issue #66)

build.sh, tools/packages.config
Update build.sh to newer version in order to get things running on Mac Os.
Update cake version in tools/packages.config to be able to build on a Mac. Things didn't work too well in mono-land, but Roslyn seems to fix things.
This unfortunately means that build must be performed with
--settings_skipverification=true
since not all things are updated at the same time.
Issue #68
=> Feature/update cake version and build sh (Issue #68)

build.cake, package-lock.json, package.json
Instead of setting a new version number and committing a new
package.json after every local build, modify the task to only
update version number when running CI-builds.
=> Feature/dont update version on local build issue #70

src/addPackage/actions/handleDirectiveWithContent.ts
By default, the byline library ignores empty lines, and doesn't do
anything with them. Since we want to keep these, we need to add the
keepEmptyLines option.
Fixes #93
=> (GH-93) Handle empty lines when reading file stream

package.json, src/bootstrapper/cakeBootstrapper.ts
Now that bootstrapper stubs exists on the resources repository, and the
additional redirects have been added into the Cake website, provide the
ability to download these from the bootstrapper command.
Fixes #432
=> (GH-432) Add additional bootstrapper downloads

src/addPackage/actions/handleDirectiveWithContent.ts
When running the command to add addin/tool/module to a .cake file, make
sure to save any dirty files, before making the change.
Fixes #429
=> (GH-429) Save all files before applying changes

README.md, package.json, src/cakeMain.ts, src/codeLens/cakeRunTaskCommand.ts, src/extensionSettings.ts
to configure the build script to be used for "Code Lens" and "Run Task"
fixes #143 
fixes #409 
This PR makes configuration of the build script for the "Run Task" command and for "Code Lens" possible.
Currently both are fixed to `./build.sh` for non-Windows and `powershell [...] build.ps1` for Windows.
Using this modification it is possible to have different configurations for the build script using a default value and also using platform-dependent values.
The "current" build script as given in the code would translate to the followin setting of `cake.taskRunner.buildScript`:
```json
{
"default": "./build.sh",
"win32": "powershell -ExecutionPolicy ByPass -File build.ps1"
}
```
However, if this was to be set in `package.json`, the setting would always contain a value for `win32`. Therefore …
=> (GH-143) added buildScript setting

src/cakeMain.ts
if more than one cake file is found.
fixes #438 
if only one Cake file exists in the project everything looks as before. 
If there are more Cake files found, the name of the file will be added to the selection:
=> (GH-438) add the file name to the "Run Task" command,

package.json
for errors during script compilation.
(Not for errors during script execution, though)
fixes #32 
Using this `problemMatcher` an output in the console that looks like this:
```
❯ .\build.ps1 -Script .\bob.cake
Preparing to run build script...
Running build script...
D:/_dev/test-123/bill.cake(22,24): error CS1002: ; expected
D:/_dev/test-123/bob.cake(6,5): error CS0102: The type 'Submission#0' already contains a definition for 'target'
D:/_dev/test-123/bob.cake(7,5): error CS0102: The type 'Submission#0' already contains a definition for 'configuration'
D:/_dev/test-123/bob.cake(30,11): error CS0229: Ambiguity between 'target' and 'target'
Error: Error(s) occurred when compiling build script:
D:/_dev/test-123/bill.cake(22,24): error CS1002: ; expected
D:/_dev/test-123/bob.cake(6,5): error …
```
=> (GH-32) added a simple problemMatcher

README.md, package.json, src/cakeMain.ts, src/documentSymbols/cakeDocumentSymbolProvider.ts, src/extensionSettings.ts
This is a rebased version of #101. Therefore, #101 is superseded by this PR.
In addition to the code provided by @Tdue21 I only added small modifications that were necessary due to the modified codebase and some documentation.
I also made three significant changes: 
* I renamed everything form `codeOutline` to `symbolProvider` to more accurately represent what is being done instead of what is the intended outcome.
* I removed the `showCodeOutline` option, as it wasn't used.
* I moved the test for cancelation (i.e. `cancellationToken.isCancellationRequested`) from once at the start to inside the `for` loop, as that is the long-running part.
=> (GH-99) Simple support for codeSymbols

README.md, package.json, src/cakeMain.ts, src/codeLens/cakeDebugTask.ts, src/codeLens/cakeRunTaskCommand.ts, src/debug/cakeDebugCommand.ts, src/debug/cakeTool.ts, src/extensionSettings.ts, src/install/actions/installCake.ts
@gep13 I did two things different to what you did in the video:
* I removed the `windows` property from settings and added an object with `default` and `win32` like I've done with the launchCommand.
* I fixed the reason debugging did not work during the video: I removed the quotes (`"`) from the target. Not sure why this is a problem but debugging does not work (any longer) when they are present.
=> (GH-376) CodeLens debugging using global tool

.depcheckrc.json, package-lock.json, package.json, src/shared/utils/getFetchOptions.ts, src/shared/utils/readConfigFile.ts, test/addPackage/actions/handleSearchResponse.test.ts
none of which were any more in use.
Also, added depcheck as tool to report on unused dependencies.
Additionally I needed to switch from the old `<>` casting to the newer casting using `as` as depcheck otherwise interprets the code (wrongly) as `tsx`.
fixes #463
=> (GH-463) removed dependencies: make-dir, npm and expect

README.md, package.json, src/extensionSettings.ts
=> (GH-461) `launchCommand` now defaults to .NET Tool

src/cakeMain.ts, src/codeLens/cakeDebugTask.ts, src/codeLens/cakeDebugTaskCommand.ts, src/codeLens/cakeRunTaskCommand.ts, src/codeLens/shared.ts, src/debug/cakeDebugCommand.ts, src/debug/cakeTool.ts, src/shared/version.ts, test/shared/shared.test.ts, test/shared/version.test.ts
Checking for installed version of Cake.Tool, as well as
installing and updating  is now centralized and not longer
done in two places.
Additionally a check for a newer version of the Cake.Tool
was implemented.
To not ask for an update *every* time the version is checked,
a "Do not update to this version"-Function was implemented.
fixes #460
=> (GH-460) implemented updating of the Cake.Tool

src/cakeMain.ts, src/codeLens/shared.ts, src/debug/cakeDebugCommand.ts, src/install/actions/index.ts, src/install/actions/installCake.ts, src/install/cakeInstallCommand.ts, src/install/installOptions.ts, src/shared/cakeDebug.ts, src/shared/cakeTool.ts, src/shared/enums.ts, src/shared/index.ts, src/shared/interfaces.ts, src/shared/messages.ts
When installing Cake to the current workspace, if installed debug
support, check which type of debugger they would like to install.
Refactored a little bit of code to get things to work, I suspect that
there are further refactorings that could be done.
Fixes #470
=> (GH-470) Add check for which debugger to install

README.md, package.json, src/cakeMain.ts, src/extensionSettings.ts
unless configured not to, using `cake.taskRunner.installNetTool`
set to `false`.
This was done by replacing the `ShellExecution` with a `CustomExecution`.
=> (GH-409) "Run Task" now always installs .NET Tool

recipe.cake
This was updated automatically as a result of a dependabot PR, so make
sure to use same version for Cake build.
=> (build) Update to latest TypeScript

package-lock.json, package.json
There is a known issue with using the latest 3.x release of node-fetch,
so for now, pin to the last release of the 2.x release.
Fixes #609
=> (#609) Revert to earlier node-fetch

src/bakery/cakeBakery.ts
This will ensure the default also works on Linux and Mac.
Fixes #719
=> Use dll instead of exe for Cake Bakery
